### ISSUE TITLE
Use setup.py rather than flit

### ISSUE THREAD

**Issue by toddrme2178** [jupyter/testpath#2]
Wheels are good for end-users who want to install the package on their system, but can't be used for packages like Linux packages and Anaconda.  It is possible to download tarballs from github, but that doesn't work with packaging-related tools like py2pack and distro scripts that scan pypi for updates.  And github does weird things with package names that makes it harder for distro scripts that check package integrity.  

And all of these issues apply not only to this package, but also to flit itself, which doesn't appear to be readily available on most downstreams yet.

So using flit saves 8 lines of code (excluding whitespace), pretty much all of which is boilerplate that will never need to be changed, while making things considerably more difficult for downstream packagers.

**Comment by takluyver** [comment]
On the other hand, the fact that it's declarative metadata should mean that distros can reuse it to create packages without having to mess around patching distutils. I'm thinking about making a flit -> conda tool to do just that.

I know flit will cause distro packagers some discomfort simply because it's not the toolchain they're used to. But that seems like a poor reason not to experiment with new tools.

Finally, I don't feel like distro packaging does much for me as an upstream developer, so I'm not particularly inclined to accommodate it. We no longer recommend that anyone install IPython/Jupyter through their Linux distro packages, because they'll almost always get an out of date version, and then we get bug reports for stuff that already changed.

**Comment by cournape** [comment]
I would second the plea of the OP. Not having a tarball is inconvenient for most downstream packagers. It is not just a tooling issue: for QA purposes, you do want to have access to a well known source of truth for the sources.

What is likely to happen in practice is that people will simply hack around the wheel to get the sources.

**Comment by SnarkBoojum** [comment]
If the release are tagged on github, then we have the tarballs ; I'll be happy to package in Debian if you do just that.
