### ISSUE TITLE
Missing setup.py, no license...

### ISSUE THREAD

**Issue by SnarkBoojum** [jupyter/testpath#3]
It looks like there is no setup.py, and I don't see the license anywhere else...

I'm pondering packaging Jupyter in Debian, so I would need to know where things stand quite precisely.

Thanks.

**Comment by takluyver** [comment]
It's MIT licensed; I'll add a licence file soon.

It's packaged using flit, which doesn't require setup.py. The metadata is
stored in flit.ini instead. I know that in the short term this will be an
inconvenience for distro packaging, but ultimately using declarative
metadata instead of an executable script should be an advantage. I don't
want to add a setup.py, but I'm happy to help work out what's needed to do
distro packaging using flit.ini.

**Comment by SnarkBoojum** [comment]
Good! Now I think I should be able to package it in Debian : even if the last release doesn't have the copyright+license statement, the fact that you clarified the situation helps!
